- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "docs"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "dev"
  color: "7c2bc8"
  description: "Developers team"
- name: "empty"
  color: "bfdadc"
  description: "Note for myself"
- name: "feature"
  color: "006b75"
  description: "Feature for project"
- name: "git"
  color: "bfdadc"
  description: "Github things"
- name: "help"
  color: "008672"
  description: "Extra attention is needed"
- name: "img"
  color: "6697F1"
  description: "Design things"
- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"
- name: "question"
  color: "d876e3"
  description: "Further information is requested"
- name: "smm"
  color: "48959B"
  description: "SMM Team"
- name: "solved"
  color: "2F73C5"
  description: "Case are solved"
- name: "todo"
  color: "C69C22"
  description: "Work-Walk?"
- name: "web"
  color: "46AC05"
  description: "Web developers"
- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"